FROM node:22-alpine AS build
WORKDIR /app

ARG VITE_CONTENTFUL_SPACE_ID
ARG VITE_CONTENTFUL_ACCESS_TOKEN
ARG VITE_POCKETBASE_URL

ENV VITE_CONTENTFUL_SPACE_ID=$VITE_CONTENTFUL_SPACE_ID
ENV VITE_CONTENTFUL_ACCESS_TOKEN=$VITE_CONTENTFUL_ACCESS_TOKEN
ENV VITE_POCKETBASE_URL=$VITE_POCKETBASE_URL

COPY package*.json ./
RUN npm ci

COPY . .

<<<<<<< HEAD
RUN echo "SPACE_ID=$VITE_CONTENTFUL_SPACE_ID"
RUN test -n "$VITE_CONTENTFUL_SPACE_ID" && test -n "$VITE_CONTENTFUL_ACCESS_TOKEN"
=======
# Vite bakes these in at build time. Railway passes matching service
# variables as build args when declared here.
ARG VITE_CONTENTFUL_SPACE_ID
ARG VITE_CONTENTFUL_ACCESS_TOKEN
ARG VITE_POCKETBASE_URL
ARG VITE_ADMIN_PASSWORD
ENV VITE_CONTENTFUL_SPACE_ID=$VITE_CONTENTFUL_SPACE_ID \
    VITE_CONTENTFUL_ACCESS_TOKEN=$VITE_CONTENTFUL_ACCESS_TOKEN \
    VITE_POCKETBASE_URL=$VITE_POCKETBASE_URL \
    VITE_ADMIN_PASSWORD=$VITE_ADMIN_PASSWORD
>>>>>>> bd01eea600206d482dd183ba2dc13887803f6b94

RUN npm run build

FROM caddy:2-alpine
COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=build /app/dist /usr/share/caddy